adminUser:
  password: vault:roachdaffodil/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:roachdaffodil/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:roachdaffodil/prow:hmacToken
segmentWriteKey: vault:roachdaffodil:segmentWriteKey
